{
 "title": "Golden Signals",
 "time": { "from": "2026-10-01T22:14:44.618Z", "to": "2026-10-01T22:55:51.820Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency (proxy: req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(quicknotes_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic (by response code)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(quicknotes_http_responses_by_code_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(quicknotes_http_responses_by_code_total{code=~\"4..|5..\"}[5m]))\r\n/\r\nsum(rate(quicknotes_http_responses_by_code_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "quicknotes_notes_total", "legendFormat": "__auto" }
   ]
  }
 ]
}